spring:
  application:
    name: WAGUWAGU-review

  datasource:
    url: jdbc:mysql://localhost:3306/review?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

